# Generated by Django 3.2.3 on 2021-05-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='yar',
            new_name='year',
        ),
    ]
