version: '3.8'

services:
  movies:
    build: ./app
    command: >
      sh -c "python manage.py  wait_for_db &&
       python manage.py migrate &&
       python manage.py runserver 0.0.0.0:8000"
     
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - movies-db
  movies-db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=movies
        - POSTGRES_PASSWORD=movies
        - POSTGRES_DB=movies_dev
  
volumes:
    postgres_data: